### ISSUE TITLE
Multiple location support

### ISSUE THREAD

**Issue by nickjupp** [MattJeanes/TeslaMateAgile#13]
Question - Is there a way to support different geofences in different Octopus regions?
I'm guessing not as is from the documentation and variables, but could I run 2 docker instances of TeslaMateAgile, one for each location, against the same TeslaMate instance?

**Comment by MattJeanes** [comment]
Presumably you'd also want to use a different geofence id as well, yes I would recommend setting up multiple instances of TeslaMateAgile that should be no problem at all!

**Comment by MattJeanes** [comment]
Let me know if you run into issues setting this up, I've not tried it before but running multiple instances as long as they have different geofence ids should be absolutely fine 🙂

**Comment by nickjupp** [comment]
Thanks... worked a treat
