### ISSUE TITLE
Change Port from Database

### ISSUE THREAD

**Issue by doenerklaus** [MattJeanes/TeslaMateAgile#14]
Hi Matt,

nice work you have done here :)
Is there a way to change the default port of the database?

Thanks

**Comment by MattJeanes** [comment]
Yes you should just be able to include it as part of the DATABASE_HOST environment variable, for example `DATABASE_HOST=database:3699`

It should match whatever your TeslaMate container is set to

**Comment by doenerklaus** [comment]
Thanks for your fast answer.

When i change the database environment to
`DATABASE_HOST=database:3699`

The application tries to connect to 
`database:3699:5432`

The port 5432 must be hardcoded somewhere

**Comment by MattJeanes** [comment]
Ah very interesting, so it does! I've released version [v1.4.1](https://github.com/MattJeanes/TeslaMateAgile/releases/tag/v1.4.1) with a DATABASE_PORT option - can you give that a go and see if it's all good?

**Comment by doenerklaus** [comment]
It's working fine now. Thanks, you are great

**Comment by MattJeanes** [comment]
Glad to hear, you're welcome! 😄
