### ISSUE TITLE
Grid rent

### ISSUE THREAD

**Issue by Dezzorex** [MattJeanes/TeslaMateAgile#15]
Hi,

Would it be possible to add a configurable grid rent fee? I rent an apartment and therefore i use this addon with teslamate to calculate how much i have to pay to my landlord (who uses tibber so I can calculate prices from there) for my car charging. Currently i have to add the 0.4833NOK per kWh on in another calculation on the side. It would be great to make it possible to add this automatically in some config so that it is added together with the variable fee.

**Comment by MattJeanes** [comment]
Hey @Dezzorex, thanks for your interest!

I have added a special option to add a flat fee per kWh now in [v1.4.2](https://github.com/MattJeanes/TeslaMateAgile/releases/tag/v1.4.2) with new environment variable `TeslaMate__FeePerKilowattHour` - can you give it a go and let me know if it meets your needs? I can see this being potentially useful for other people too 😄

**Comment by Dezzorex** [comment]
Hi, this looks great. But actually it looks like this tool is working for me, i thought it was working, but seems like it just uses the price I added in the GUI a while back, and if i set it to NULL i get the following. I suspect its due to my subscription still won't be active untill next week I guess, but i can get data directly from the API, but perhaps the price range isn't working. What kind of data/date-type is used to query the prices in between the offsets? Have been quickly looking at it, but I don't get the right datatype it seems to just test the query with my own API key (I get current data without any problems). Do you have an example for range priceinfo?

info: TeslaMateAgile.PriceHelper[0]
      Calculating cost for charges 01/06/2021 23:00:53 UTC - 01/07/2021 06:01:13 UTC
fail: TeslaMateAgile.PriceHelper[0]
      Failed to calculate charging cost / energy for charging process 5
System.Exception: Mismatch of requested price info from Tibber API (expected: 9, actual: 0)
   at TeslaMateAgile.Services.TibberService.GetPriceData(DateTimeOffset from, DateTimeOffset to) in /src/TeslaMateAgile/Services/TibberService.cs:line 114
   at TeslaMateAgile.PriceHelper.CalculateChargeCost(IEnumerable`1 charges) in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 76
   at TeslaMateAgile.PriceHelper.Update() in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 54

**Comment by Dezzorex** [comment]
Fantastic work, it works great! @MattJeanes  If you ever get bored and  want to make an integration towards Evlia API (Norwegian grid prices) that would be even more perfect ;-) 

https://assets.ctfassets.net/jbub5thfds15/1mF3J3xVf9400SDuwkChUC/d959c5440712df029a8ce29a49403f1c/Elvia__nettleie-API.pdf

**Comment by MattJeanes** [comment]
Great to hear! If you'd like to raise another issue for that one I can have a look...!
