### ISSUE TITLE
Specifying an invalid GeofenceID does not throw errors

### ISSUE THREAD

**Issue by kimma** [MattJeanes/TeslaMateAgile#24]
There seems to be no check for the existence of a GeoFenceID in the teslamate DB.
This results in the application running just fine, but never actually finding any charging sessions to update.

Consider adding a check for validity of the geofence id on each "update run", in case it does not exist (either by being deleted in between runs, or by being configured with the wrong ID).
Also consider adding logging to show the configured GeofenceID and Name of the geofence when executing an "update run", so that it will be a bit more obvious if the wrong GeofenceID has been configured.

**Comment by MattJeanes** [comment]
That's a nice QoL idea, I am assume you found this out the hard way! 😄

**Comment by MattJeanes** [comment]
I've added this in the next update [`v1.8.2`](https://github.com/MattJeanes/TeslaMateAgile/releases/tag/v1.8.2) now, here's how it looks in the logs:
![image](https://user-images.githubusercontent.com/2363642/146242361-c35fcb52-6e6a-4127-b886-18f6ceec7d2e.png)
![image](https://user-images.githubusercontent.com/2363642/146242584-0005769c-d622-4b86-9c22-143422affcfe.png)

I've also added a warning if you have a cost per unit set on the geofence which will also break TeslaMateAgile:
![image](https://user-images.githubusercontent.com/2363642/146242647-c24a67fd-a182-451d-a9d2-1d05801ce025.png)

**Comment by kimma** [comment]
> That's a nice QoL idea, I am assume you found this out the hard way! 😄
Indeed! When configuring and testing i apparently had "TeslaMate__UpdateIntervalSeconds and TeslaMate__GeofenceId" right below each other in the configuration, and when i was happy i promptly set the GeofenceID to 3600 and left the UpdateInterval on 30 😅  
Took a couple of months before i went to check charging cost so far this year.
Luckily it worked flawless to automatically update previous charging sessions months back!

**Comment by MattJeanes** [comment]
Whoops! Well if it happens again hopefully you'll see the new warnings 😄
