### ISSUE TITLE
Configured geofence 'Home' (id: 1) has a cost per unit set which will prevent TeslaMateAgile from working properly

### ISSUE THREAD

**Issue by thunder2k** [MattJeanes/TeslaMateAgile#26]
Hi,
I'm seeing this error in the logs.

These are the relevant configs from the yaml file:
      - TeslaMate__UpdateIntervalSeconds=300
      - TeslaMate__GeofenceId=1
      - TeslaMate__EnergyProvider=FixedPrice
      - FixedPrice__TimeZone=Etc/UTC # IANA (tz database) time zone code, used for below times
      - FixedPrice__Prices__0=23:16-08:16=0.0523 # Night
      - FixedPrice__Prices__1=08:16-23:16=0.1818 # Day
 
This is my geo-fence config in teslamate:
![image](https://user-images.githubusercontent.com/43518960/151822998-10a6e3cd-f039-4909-81b2-30f1867c15fc.png)

I'm running teslmate 1.26.1.

Any help is appreciated.

Thanks!

**Comment by MattJeanes** [comment]
Hey, you need to unset the cost for the geofence in TeslaMate for TeslaMateAgile to work correctly, as per the warning

**Comment by MattJeanes** [comment]
Yeah it's just a warning as if TeslaMate calculates your charge TeslaMateAgile will ignore it, so we warn users to turn off this feature. That's a good idea for updating the message I think you're right in that it's not clear enough. You need to set it to blank instead of zero, here's what mine looks like which works without warning:

**Comment by MattJeanes** [comment]
Oh, that makes more sense haha! I've updated the warning which will go out whenever I release a new update (I won't do one just for that!):

` Configured geofence '{geofence.Name}' (id: {geofence.Id}) should not have a cost set in TeslaMate as this may override TeslaMateAgile calculation`

Hopefully that one is clearer, I'm open to feedback!
