### ISSUE TITLE
Entsoe transparency API provider support

### ISSUE THREAD

**Issue by oivindoh** [MattJeanes/TeslaMateAgile#28]
Many people (in the Nordpool spot areas in particular) have spot price contracts that follow the spot price per hour for their area - similar to what's fetched in the Tibber integration ( #12 ). Usually these contracts have some kind of fixed addition (can be negative, 0 or positive - included already in Tibber data) to the spot price, so this addition could be configurable.

There is a more generic pricing API delivered by [entsoe](https://www.entsoe.eu/) called the "transparency API" where interested parties can download future (day-head) and historical spot prices for each price area (e.g. I'd personally fetch prices for the [NO3 price area](https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&dateTime.dateTime=08.01.2020+00:00|CET|DAY&biddingZone.values=CTY|10YNO-0--------C!BZN|10YNO-3--------J&resolution.values=PT15M&resolution.values=PT30M&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)) (link is to price data for jan 8th 2020).

They have an [API user guide](https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html), and API access is requested after [registering an account](https://transparency.entsoe.eu/protected-url) by sending an email with the subject "Restful API access" to transparency@entsoe.eu, with your registered email address in the message body. Token for access is [created manually](https://iop-transparency.entsoe.eu/content/static_content/download?path=/Static%20content/API-Token-Management.pdf) after logging in and having API access granted.

I think the ability of fetching price data from this API based on a selectable (or even dynamic based on positution) price area would be a very valuable addition to TMA. I'll be experimenting a bit with fetching data from entsoe in a small python project and might try my luck at C# if I manage to finish that project.

**Comment by MattJeanes** [comment]
Hey this sounds great, have you seen the work being done in #27? I wonder if this largely covers the use cases you're interested in here

**Comment by oivindoh** [comment]
Ah! No I had not - that would at least cover my specific use case I believe, though AFAIK Nordpool have terms that prohibit scraping / "automated extraction", and a somewhat expensive API license if one decides to play by their rules, whereas Entsoe does not, while also providing price data for areas outside the Nordpool area.

**Comment by oivindoh** [comment]
Closing this since https://github.com/MattJeanes/TeslaMateAgile/pull/27 is more than sufficient in my Nordpool case, at least until they break their APIs.
