### ISSUE TITLE
Unable to calculate cost of some charges

### ISSUE THREAD

**Issue by PalleRaa** [MattJeanes/TeslaMateAgile#41]
I have a few charges where the price will not be calculated. I am using Energinet to provide the prices and it oftens works, but in some cases it does not.

Here is the log from the attempt to calculate the cost for this single charge "452"

Any idea what is wrong?

```
dbug: TeslaMateAgile.PriceService[0]
      Updating prices
info: TeslaMateAgile.PriceHelper[0]
      Looking for finished charging processes with no cost set in the 'Home' geofence (id: 4)
info: TeslaMateAgile.PriceHelper[0]
      Calculating cost for charges 05/23/2023 13:33:21 UTC - 05/23/2023 15:00:10 UTC
dbug: TeslaMateAgile.PriceHelper[0]
      Retrieved 5 prices:
dbug: TeslaMateAgile.PriceHelper[0]
      05/23/2023 10:00:00 UTC - 05/23/2023 11:00:00 UTC: 0.87898751125
dbug: TeslaMateAgile.PriceHelper[0]
      05/23/2023 11:00:00 UTC - 05/23/2023 12:00:00 UTC: 0.69429999125
dbug: TeslaMateAgile.PriceHelper[0]
      05/23/2023 12:00:00 UTC - 05/23/2023 13:00:00 UTC: 0.52374999750
dbug: TeslaMateAgile.PriceHelper[0]
      05/23/2023 13:00:00 UTC - 05/23/2023 14:00:00 UTC: 0.51081250
dbug: TeslaMateAgile.PriceHelper[0]
      05/23/2023 14:00:00 UTC - 05/23/2023 15:00:00 UTC: 0.58975000250
info: TeslaMateAgile.PriceHelper[0]
      Phase correction: 2 -> 3
dbug: TeslaMateAgile.PriceHelper[0]
      Calculated charge cost for 05/23/2023 13:00:00 UTC - 05/23/2023 14:00:00 UTC (unit cost: 0.51081250, fee per kWh: 0): 2.4673334913608334581895300000 for 4.83021361333333357776 energy
dbug: TeslaMateAgile.PriceHelper[0]
      Calculated charge cost for 05/23/2023 14:00:00 UTC - 05/23/2023 15:00:00 UTC (unit cost: 0.58975000250, fee per kWh: 0): 6.4808319197627931300064801272 for 10.98911724000000005088 energy
fail: TeslaMateAgile.PriceHelper[0]
      Failed to calculate charging cost / energy for charging process 452
      System.Exception: Charge calculation failed, pricing calculated for 255 / 256, likely missing price data
         at TeslaMateAgile.PriceHelper.CalculateChargeCost(IEnumerable`1 charges) in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 127
         at TeslaMateAgile.PriceHelper.Update() in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 64
dbug: TeslaMateAgile.PriceService[0]
      Price update complete
```

**Comment by PalleRaa** [comment]
I would love to do that. If only I knew how. Can you give me a short "how to"?

**Comment by MattJeanes** [comment]
I've provided a short how to on another issue before, see if this helps if not I'll be happy to walk you through it: https://github.com/MattJeanes/TeslaMateAgile/issues/17#issuecomment-772895618

**Comment by PalleRaa** [comment]
Never used pgAdmin before, or even logged into the database. But for some reason it just worked. Amazing. I have attached the .csv file. Let me know if it is not what you asked for.

[data-1685037097905.csv](https://github.com/MattJeanes/TeslaMateAgile/files/11567878/data-1685037097905.csv)

**Comment by MattJeanes** [comment]
Nice! That's one part of what I need, the other is the entries from the `charges` table for that `charging_process_id`

The query should be `SELECT * FROM charges WHERE charging_process_id = 452`

**Comment by PalleRaa** [comment]
Like so?
[data-1685041452114.csv](https://github.com/MattJeanes/TeslaMateAgile/files/11568426/data-1685041452114.csv)

**Comment by MattJeanes** [comment]
That's perfect, thank you. I'll take a look and see what went wrong here.

**Comment by MattJeanes** [comment]
Okay it looks very similar to an issue I recently-ish pushed a fix for with version [v1.11.3](https://github.com/MattJeanes/TeslaMateAgile/releases/tag/v1.11.3)

Can you verify that you're on that version? If you're on an older one I suspect that will be why 😄

**Comment by PalleRaa** [comment]
That would be slightly embarrassing if I am not on the latest release. Let me double check that later when I get home.

**Comment by PalleRaa** [comment]
Updated to latest release (1.11.3) and now all charges calculates correctly.

**Comment by MattJeanes** [comment]
Great to hear, thanks for the confirmation! 🙂
