### ISSUE TITLE
Unable to download docker image

### ISSUE THREAD

**Issue by darek-margas** [MattJeanes/TeslaMateAgile#46]
I tried to download image, however, it says access is denied or image does not exist.

**Comment by MattJeanes** [comment]
What command(s) and/or docker-compose file are you using to download this? The image is hosted on DockerHub and you can see the various tags here https://hub.docker.com/repository/docker/mattjeanes/teslamateagile/tags?page=1&ordering=last_updated

**Comment by darek-margas** [comment]
Thanks, now it worked:
`root@ubuntu:~# docker pull mattjeanes/teslamateagile
Using default tag: latest
latest: Pulling from mattjeanes/teslamateagile
14726c8f7834: Pull complete
6c3981608c2b: Pull complete
a2e354eccee4: Pull complete
cbca4ad4689c: Pull complete
b6278aed9c56: Pull complete
4f4fb700ef54: Pull complete
cdfa249b731e: Pull complete
Digest: sha256:d9b35a0922c20b71446560c50a2fca3a5fd7c22296bc2f42146b70dadd2df82b
Status: Downloaded newer image for mattjeanes/teslamateagile:latest
docker.io/mattjeanes/teslamateagile:latest
`
