### ISSUE TITLE
No data available if multiple homes exist

### ISSUE THREAD

**Issue by matze19999** [MattJeanes/TeslaMateAgile#53]
I've added another home last week because I will move in 2 months, but now no data is available anymore for the current home, because TeslaMateAgile always takes the first home which the API gives, but I need so select the second home now.

Is there a easy way to do that?

**Comment by MattJeanes** [comment]
Hi!

I believe the setting you're looking for is `TeslaMate__GeofenceId`, if you have set up another home or location there should be a new ID for that one. Check the readme for more info on how to find this number.

Hope that helps! 🙂

**Comment by MattJeanes** [comment]
Also keep in mind TeslaMateAgile can only track one location at a time so you'll need to run multiple instances of it with different settings if you want to run it with multiple locations

**Comment by MattJeanes** [comment]
Interesting! We don't appear to have support for that, but it should be easy to add.

I'm currently on holiday this week so I'll see if I can do that next week for you 🙂

**Comment by matze19999** [comment]
Thank you, this would be amazing!

Reach out to me if I can help you somehow😊

**Comment by MattJeanes** [comment]
Might need some help to test it so I certainly will!

**Comment by MattJeanes** [comment]
Hi again! This functionality is now available in the latest version v1.14.0 🙂 

Check the readme for information about `Tibber__HomeId` and let me know how it goes!

**Comment by matze19999** [comment]
It works great, thank you for this update! 😊

**Comment by MattJeanes** [comment]
Awesome! No problem 🙂
