### ISSUE TITLE
Feature request: monitoring multiple geofence IDs

### ISSUE THREAD

**Issue by goncal** [MattJeanes/TeslaMateAgile#55]
It would be great if I could monitor a couple of different geofence IDs (two homes that have the same tariff) with a single instance of teslamate agile.
Is that possible at all?

**Comment by MattJeanes** [comment]
Hi there, it would in theory be possible yes but given you can achieve the same effect by just running two containers / instances of TeslaMateAgile with slightly different configuration on the geofence ID and your use case being quite unusual I don't think this is worth the effort of implementing so I'm going to close this and recommend you do that instead. Sorry, hope you understand!

**Comment by goncal** [comment]
I fully agree with that view. It would only make sense if it was a trivial change.
Setting up an additional container is no problem at all.
Thanks for sharing this very useful work!

**Comment by MattJeanes** [comment]
And thank you for your understanding! 🙂
