### ISSUE TITLE
Unable to connect to testamate

### ISSUE THREAD

**Issue by blue-eric** [MattJeanes/TeslaMateAgile#61]
Hello, according to the Docker configuration file, after I made the configuration, I was unable to connect to and access testamate on the intranet, and I also couldn't see data on Grafana. I would like to ask if it is necessary to map port 5432 on the router to use your project? Also, how do I need to set up to access testamate normally on the intranet? When I used the testamate project before, I only mapped the 3000 port as a router, and the 4000 port does not need to be mapped on the intranet. Thank you for your answer. Here is my Docker configuration

version: "3"

services:

  teslamateagile:
    image: mattjeanes/teslamateagile:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=123456
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - TeslaMate__UpdateIntervalSeconds=300  
      - TeslaMate__GeofenceId=11
      - FixedPrice__TimeZone=Asia/Shanghai      
      - TeslaMate__EnergyProvider=FixedPrice
      - FixedPrice__Prices__0=07:00-11:00=0.5783
      - FixedPrice__Prices__1=11:00-13:00=0.3783
      - FixedPrice__Prices__2=13:00-22:00=0.5783
      - FixedPrice__Prices__3=22:00-07:00=0.3783  
      - ENCRYPTION_KEY=123456
      - VIRTUAL_HOST=192.168.50.74
      - TZ=Asia/Shanghai
      - MQTT_HOST=mosquitto
      - MQTT_USERNAME=tesla
      - MQTT_PASSWORD=234567
      - MQTT_PORT=1883
      - Logging__LogLevel__Default=Debug
      - Logging__Console__FormatterName=simple
      - "Logging__Console__FormatterOptions__TimestampFormat=yyyy-MM-dd HH:mm:ss.fff "
      - TeslaMate__LookbackDays=
      - TeslaMate__Phases=
      - DATABASE_PORT=5432
    ports:
      - 4025:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=teslamate
      - TZ=Asia/Shanghai
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: ccr.ccs.tencentyun.com/dhuar/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=123456
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - TZ=Asia/Shanghai  
    ports:
      - 3010:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data
volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:

**Comment by MattJeanes** [comment]
Hey, the time zone mainly affects the fixed price provider as it will interpret your times under the selected timezone. Everything gets normalised to UTC in the output logs but the data should be correct

**Comment by MattJeanes** [comment]
You can define it with any IANA timezone code but the logs will not show this as your dates are converted into UTC when the app starts up. The logs are only really designed to be used for debugging, the calculated value will appear in Grafana. If you convert the timezone in the logs back to your configured time zone it should all add up.

**Comment by MattJeanes** [comment]
Yes you can have multiple instances of TeslaMateAgile running as long as they are using a different geofence ID

**Comment by MattJeanes** [comment]
Looks like we didn't close this one off before, glad I could help!
