### ISSUE TITLE
help with Fixed Price (Weekly)

### ISSUE THREAD

**Issue by darkh89** [MattJeanes/TeslaMateAgile#81]
I am encountering an issue with TeslaMateAgile using the FixedPriceWeekly provider. 
The service fails to start and logs the following error:

> fail:` TeslaMateAgile.PriceService[0]
>       Failed to update prices
>       System.ArgumentException: Invalid fixed price data, covers more than 24 hours

my compose file:
>   teslamateagile:
>     image: mattjeanes/teslamateagile:latest
>     restart: always
>     environment:
>       - DATABASE_USER={Myuser}
>       - DATABASE_PASS={Mypassword}
>       - DATABASE_NAME={mydatabase}
>       - DATABASE_HOST=database
>       - TeslaMate__UpdateIntervalSeconds=3600
>       - TeslaMate__GeofenceId=2
>       - TeslaMate__EnergyProvider=FixedPriceWeekly
>       - TeslaMate__LookbackDays=365 # Only calculate charges started in the last x days (default: null, all charges)
>       - FixedPriceWeekly__TimeZone=Europe/Zurich # IANA (tz database) time zone code, used for below times
>       - FixedPriceWeekly__Prices__1=Mon-Fri=22:00-07:00=0.25 
>       - FixedPriceWeekly__Prices__2=Mon-Fri=07:00-22:00=0.36 
>       - FixedPriceWeekly__Prices__5=Sat,Sun=22:00-17:00=0.25 
>       - FixedPriceWeekly__Prices__6=Sat,Sun=17:00-22:00=0.36 
>       - FixedPriceWeekly__Prices__7=Sun,Mon=22:00-07:00=0.25 
> 

I am trying to configure the rates provided by my energy supplier:

Weekdays:
Off-peak hours: 00:00 to 07:00 / 22:00 to 00:00
Peak hours: 07:00 to 22:00

Weekend:
Off-peak hours: 00:00 to 17:00 / 22:00 to 24:00
Peak hours: 17:00 to 22:00

What I am specifically trying to ensure is:

1. From Friday at 22:00 to Saturday at 17:00, the rate is considered off-peak.

1. From Sunday at 22:00 to Monday at 07:00, the rate is also considered off-peak.

Thank you for your help on this.

**Comment by MattJeanes** [comment]
@darkh89 you managed to get it all sorted? What was the issue in the end?

**Comment by darkh89** [comment]
Hi @MattJeanes, 

I've changed my configuration file to handle this:

>  # Monday to Friday
>       - FixedPriceWeekly__Prices__0=Mon-Fri=00:00-07:00=0.25 
>       - FixedPriceWeekly__Prices__1=Mon-Fri=07:00-22:00=0.36 
>       - FixedPriceWeekly__Prices__2=Mon-Fri=22:00-00:00=0.25 
> 
> # Saturday
>       - FixedPriceWeekly__Prices__3=Sat=00:00-17:00=0.25 
>       - FixedPriceWeekly__Prices__4=Sat=17:00-22:00=0.36 
>       - FixedPriceWeekly__Prices__5=Sat=22:00-00:00=0.25 
> 
> # Sunday to Monday
>       - FixedPriceWeekly__Prices__6=Sun=00:00-17:00=0.25 
>       - FixedPriceWeekly__Prices__7=Sun=17:00-22:00=0.36 
>       - FixedPriceWeekly__Prices__8=Sun=22:00-00:00=0.25

**Comment by MattJeanes** [comment]
Ah okay makes sense, good to hear you got it sorted!
